### ISSUE TITLE
One-shot mode

### ISSUE THREAD

**Issue by mmalenic** [cargo-lambda/cargo-lambda#153]
It would be cool to have a feature that allows starting the lambda server and invoking all in one go. This would be useful in automated testing, in order to avoid running `cargo lambda watch` and then waiting until the server is ready before running `cargo lambda invoke`.

This could take the form of a new flag in `cargo lambda watch`, such as `--one-shot`, which takes the arguments of `cargo lambda invoke`, executing them after starting the server. I'm not sure how easy this would be to accomplish using clap though.

Let me know your thoughts.

**Comment by calavera** [comment]
I'm not sure if I understand how useful this would be. That sounds like it could just be a unit test in our codebase. What's the benefit of starting the process and terminating it after the first call?

**Comment by mmalenic** [comment]
Thanks for the response @calavera. Yeah, you might be right about the unit test, and I could've missed an obvious solution.

For some context, we are running integration tests for our lambda function using example api gateway proxy events, such as [this one](https://github.com/awsdocs/aws-lambda-developer-guide/blob/main/sample-apps/nodejs-apig/event.json). The tests are run by spawning `cargo lambda watch` and running `cargo lambda invoke` using Rust's [Command](https://doc.rust-lang.org/std/process/struct.Command.html). This is done asynchronously, and `cargo lambda watch` is run as a separate process since it does not terminate. However, I don't see an elegant way determine when the watch process is ready to accept incoming requests, without polling it repeatedly.

The reason the integration tests are using cargo-lambda in the first place is to be able to call the example proxy events, however there might be a better way to do this. Is there a way to directly invoke the lambda runtime with a request, and avoiding using cargo-lambda?

**Comment by calavera** [comment]
Yes, you can create a Request object from a json file without having to boot the full runtime. Look at how we tests events in the runtime, those functions are public:

https://github.com/awslabs/aws-lambda-rust-runtime/blob/main/lambda-http/src/request.rs#L346-L367
https://github.com/awslabs/aws-lambda-rust-runtime/blob/main/lambda-http/src/request.rs#L472-L501

Once you have the request object, you can call your function handle directly.

Let me know if that makes sense.

**Comment by mmalenic** [comment]
Ahh, yes, that makes sense, thanks @calavera :slightly_smiling_face:

Using that seems like a more sensible solution than running cargo-lambda.

**Comment by calavera** [comment]
great, I'm going to close this issue. Thanks a lot for opening it! I've added this testing information to the runtime README:

https://github.com/awslabs/aws-lambda-rust-runtime/pull/484
