### ISSUE TITLE
Help: cargo lambda build vs. openssl

### ISSUE THREAD

**Issue by dholroyd** [cargo-lambda/cargo-lambda#182]
Attempting to `cargo lambda build` a project that transitively depends on openssl fails with,

```
build/expando.c:2:10: fatal error: 'openssl/opensslconf.h' file not found                                                                                                                                 
#include <openssl/opensslconf.h>                                                                                                                                                                          
         ^~~~~~~~~~~~~~~~~~~~~~~                                                                                                                                                                          
1 error generated.                                                                                                                                                                                        
```

attempting to build with `--arm64` instead fails with,

```
pkg-config has not been configured to support cross-compilation.

Install a sysroot for the target platform and configure it via
PKG_CONFIG_SYSROOT_DIR and PKG_CONFIG_PATH, or install a
cross-compiling wrapper for pkg-config and set it via
PKG_CONFIG environment variable.
```

Is there any way to prepare my build environment so that libraries expected on the target will be available at build time, or some documentation I need to read?

For what its worth, I can use [`cross build ...`](https://github.com/cross-rs/cross) together with an awsl2-derived docker container to build the code, and that works.  I was hoping that `cargo lambda` might simplify the workflow by avoiding the need to setup a custom docker image.

**Comment by messense** [comment]
Generally when cross compiling build from source is preferred, you could activated the `vendered` feature of the openssl crate to do so.

```toml
[dependencies]
openssl = { version = "0.10", features = ["vendored"] }
```

See also https://docs.rs/openssl/latest/openssl/#vendored
