### ISSUE TITLE
Add `new` command

### ISSUE THREAD

**Issue by calavera** [cargo-lambda/cargo-lambda#21]
It'd be interesting to have a command that creates the scaffolding for lambda functions, with some way to ask for the event that the function receives.

Like `cargo new`, `cargo lambda new` would create a project locally, but the source would already have lambda code, and it would include the right dependencies.

**Comment by rainDelay9** [comment]
For a first version maybe consider integrating [cargo-generate](https://crates.io/crates/cargo-generate) with some Hello World template?

**Comment by calavera** [comment]
This is a fun one that I've been working on. I looked into cargo-generate but it does too much for what I think we need here. I'm also not a big fan of the git2 crate, which that projects depends on. I'd like to avoid libgit2 as much as possible.

**Comment by calavera** [comment]
This was added in #56 .
