### ISSUE TITLE
Docker image

### ISSUE THREAD

**Issue by calavera** [cargo-lambda/cargo-lambda#230]
It'd be nice to provide a basic docker image in every release with Zig and Cargo Lambda installed. That would fit some people's workflows that use Docker images with Docker compose.

**Comment by brahms116** [comment]
Hmmm, would something like this work...
```Dockerfile
FROM rust:slim-buster
RUN apt update
RUN apt install python3-pip -y
RUN pip3 install --upgrade pip
RUN pip3 install cargo-lambda
```

Or would we be after one without using pip3 and installing binaries directly instead?

Could also use different base image to reduce image size.
