### ISSUE TITLE
ERROR Error("data did not match any variant of untagged enum LambdaRequest")

### ISSUE THREAD

**Issue by Tandolf** [cargo-lambda/cargo-lambda#301]
I was going to try to write a lambda using rust and found this and i have had a really hard time with getting lambdas to work and how to develop a lambda locally.

i dont know if im stupid or if lambdas are very convoluted, complicated and strange.

when running:
```
cargo lambda new test-lambda
```

i answer `yes`, and then `HTTP REST`. i then `cd` into the folder `test-lambda`

and run:
```
cargo lambda watch
```

and then:
```
cargo lambda invoke --data-ascii '{ "command": "hi" }'
```

and what i get back is
```
ERROR Error("data did not match any variant of untagged enum LambdaRequest", line: 0, column: 0)
[Finished running. Exit status: 0]
```

And the entire lambda crashes and i need to restart it. 

i also try to use curl:
```
curl http://localhost:9000/lambda-url/test-lambda
```

and i get nothing back.

What am i missing?

**Comment by Clockwork757** [comment]
Http lambas run behind one of many AWS services that do the actual http handling. Those services package up all the http info and some AWS context as a JSON object which is what your lambda is expecting.

[Here's an example](https://github.com/awslabs/aws-lambda-rust-runtime/blob/main/lambda-http/tests/data/apigw_v2_proxy_request.json).

**Comment by Tandolf** [comment]
okey.

I have switched from using `cargo lambda` to using `aws sam` instead as the documentation was a lot clearer for my particular usercase (http -> lambda -> dynamoDB).

The example you posted is just a random json file without any documentation, information about properties, any use case or any explanation.
