### ISSUE TITLE
Document how to deal with native dependencies

### ISSUE THREAD

**Issue by calavera** [cargo-lambda/cargo-lambda#357]
Some major Rust crates, like `reqwest` depend on native dependencies by default, and provide alternatives to them, for example OpenSSL. Because Lambda is a self contained environment, native dependencies are discouraged, and Cargo Lambda will fail to compile with them if you run on Windows or MacOS because we cannot cross compile native code like we cross compile Rust code.

We should have a section in the docs about native dependencies and how to deal with them. In most cases, we can document the alternatives to those native dependencies because they are pretty well known.

**Comment by noahgift** [comment]
Love this tool so far!  I did run into this issue as well with rust-bert:

```
(.venv) vscode@f19e45043f99:/workspaces/rust-mlops-template/t5lambda$ make release
cargo lambda build --release
▪▪▪▪▪ Target component installed                                                                                                                             Compiling tokio v1.25.0
   Compiling futures-util v0.3.26
   Compiling tracing v0.1.37
   Compiling openssl-sys v0.9.80
   Compiling http v0.2.8
The following warnings were emitted during compilation:

warning: build/expando.c:2:10: fatal error: 'openssl/opensslconf.h' file not found
warning: #include <openssl/opensslconf.h>
warning:          ^~~~~~~~~~~~~~~~~~~~~~~
warning: 1 error generated.

error: failed to run custom build command for `openssl-sys v0.9.80`
```

**Comment by l1x** [comment]
This probably requires to install openssl dev package on the host. 

For example

```
apt install libssl-dev 
```

**Comment by noahgift** [comment]
@l1x Good point!  I primarily use GitHub Codespaces .devcontainers so this is a great use case for that style.  I will see if this is the fix and report back in a bit.
