### ISSUE TITLE
Which http library would you recommend to be used with cargo-lambda?

### ISSUE THREAD

**Issue by l1x** [cargo-lambda/cargo-lambda#370]
I was wondering if there is a recommendation which http library to use with cargo lambda. I am looking for routing and Json / Html responses primarily. Thank in advance.

**Comment by greenwoodcm** [comment]
Are you asking about a library for HTTP client or HTTP server?  It sounds to me like you're asking for HTTP server framework given the question.  `cargo-lambda` is pretty agnostic to whatever you're building inside the Lambda function.  this question might be more about an HTTP server framework to use with the [aws-lambda-rust-runtime](https://github.com/awslabs/aws-lambda-rust-runtime).

if that's your question, any web framework that ends up producing an implementation of:
```
tower::Service<http::Request<_>, http::Response>
```
should work just fine with the `lambda-http` sub-crate.  I just put an app in the examples folder of the runtime repo the other day that uses [axum](https://docs.rs/axum/latest/axum/) and the Lambda runtime.  that could be a good place to start.

https://github.com/awslabs/aws-lambda-rust-runtime/blob/main/examples/http-axum/src/main.rs

**Comment by l1x** [comment]
> Are you asking about a library for HTTP client or HTTP server?

I am asking for a library that would make cargo-lambda a perfect API solution. I need routing so map incoming requests based on http verbs and paths to Rust functions. It would be nice to be work with all the requests in the same function (called middleware for some frameworks) and handling serialization / desiralization relatively easily.

It is not a problem if something is low level. Right now I use matchit as the router and using structs from the aws libs to pass in to handler functions. Axum looks promising. Thanks.

**Comment by greenwoodcm** [comment]
Sounds good, take a look at `axum` and let us know how it goes.  I think it'll give you what you are after.  Alternatively, if you find a different HTTP framework that integrates nicely with the runtime, a PR with an example in the runtime repo would be awesome!  I'm going to close this but feel free to reopen or open a new issue if you could use more help.
