### ISSUE TITLE
command comes thru with }

### ISSUE THREAD

**Issue by davehorner** [cargo-lambda/cargo-lambda#380]
I am following along with the getting started.  I've installed via pip install cargo-lambda.  I'm running windows 10 using anaconda.

Here is the output of my invoke while I'm not running the watch (showing the extra %7D)
```
cargo lambda invoke --data-ascii '{"command": "hi"}'
Error:
  x error sending request to the runtime emulator
  |-> error sending request for url (http://127.0.0.1:9000/2015-03-31/functions/hi%7D'/

```
Here's output when invoke is run when watch is running.
```
cargo lambda watch
 INFO invoke server listening on 127.0.0.1:9000
 INFO starting lambda function function="hi}'" manifest="Cargo.toml"
error: no bin target named `hi}'`.
```

I've tried all manner of escaping and double quoting.  I'm not sure why I'm getting the extra '}'

**Comment by davehorner** [comment]
Tried a few different things

```
echo '{"command": "hi"}' > data.text                                                                                                                                          

cat data.text
'{"command": "hi"}'

cargo lambda invoke --data-file data.text
Error: serde_json::error::Error  
x expected value at line 1 column 1
```

```
echo {"command": "hi"} > data.text

cat data.text
{"command": "hi"}

cargo lambda invoke --data-file data.text
Error: serde_json::error::Error
  x data did not match any variant of untagged enum LambdaRequest
```

**Comment by bnusunny** [comment]
Are you using Windows CMD? It uses a different format. Try this: 

```
cargo lambda invoke --data-ascii "{\"command\": \"hi\"}"
```

[AWS CLI Reference](https://docs.amazonaws.cn/en_us/cli/latest/userguide/cli-usage-parameters-quoting-strings.html#cli-usage-parameters-quoting-strings-containing) has more details for different OS/Shells.

**Comment by davehorner** [comment]
Thank you for the response.  I see the reference and the escaping you provided.  I've run this command:

```
cargo lambda invoke --data-ascii "{\"command\": \"hi\"}"
Error: serde_json::error::Error

  x data did not match any variant of untagged enum LambdaRequest
```

I do see the watch process shows:
```
 INFO starting lambda function function="_" manifest="Cargo.toml"
ERROR Lambda runtime invoke{requestId="0539be0d-e04b-4fe1-a736-ad772e8641d6" xrayTraceId="Root=1-63fbfcfc-61ee6f334abd407a475e8523;Parent=4b0d9166ee526eea;Sampled=1"}: Error("data did not match any variant of untagged enum LambdaRequest", line: 0, column: 0)
```

The first lambda I created I indicated I would be using the Api Gateway HTTP Api.  I tried again creating another project and selecting "I don't know yet".  This new lambda without the api selection seems to work as expected.

Any ideas on why or what I can do about the HTTP Api Gateway HTTP Api lambda I created?  Thank you again.

**Comment by davehorner** [comment]
https://youtu.be/2MAuMihVlO0 is a screencast that explains using an API Gateway invoke.

I pulled the apigw_http feature from my original project and did another watch.
I see the response from the invoke is fine.

Not sure what is going on but now the console is just filled with pages and pages of the following:
```
ERROR Lambda runtime invoke{requestId="eb0b0e17-96b4-44f3-9f24-1b3a171400ff"}: Error("EOF while parsing a value", line: 1, column: 0)
ERROR Lambda runtime invoke{requestId="1e9bce9c-680c-48a5-8637-26c37e394b5d"}: Error("EOF while parsing a value", line: 1, column: 0)
ERROR Lambda runtime invoke{requestId="7bd85236-85a3-4b72-9cbe-e66760e26c34"}: Error("EOF while parsing a value", line: 1, column: 0)
ERROR Lambda runtime invoke{requestId="67a2e0b7-2974-4786-939f-765afc60ffab"}: Error("EOF while parsing a value", line: 1, column: 0)
ERROR Lambda runtime invoke{requestId="af9b66b5-0469-4cdf-924d-4471af42ac32"}: Error("EOF while parsing a value", line: 1, column: 0)
ERROR Lambda runtime invoke{requestId="13cbe406-9a25-4a38-9f7a-b020e0f86ad4"}: Error("EOF while parsing a value", line: 1, column: 0)
ERROR Lambda runtime invoke{requestId="b3037d32-579d-4f6e-a642-312a01ac29bc"}: Error("EOF while parsing a value", line: 1, column: 0)
ERROR Lambda runtime invoke{requestId="8ef2fb87-b5d1-4c5b-93f9-dab91fc001e1"}: Error("EOF while parsing a value", line: 1, column: 0)
ERROR Lambda runtime invoke{requestId="730dd0e6-aa3c-453e-b23b-a197355a3ae4"}: Error("EOF while parsing a value", line: 1, column: 0)
ERROR Lambda runtime invoke{requestId="b5113a2f-0884-4a8a-afdd-d331b7bb0b6b"}: Error("EOF while parsing a value", line: 1, column: 0)
```

I'm not sure if I should create another ticket or not but that is concerning.

**Comment by bnusunny** [comment]
I see. For API Gateway triggered lambda functions, they expect the events match the schema sent by API Gateway. You can see the example events [here](https://github.com/awslabs/aws-lambda-rust-runtime/tree/main/lambda-http/tests/data). 

To make it simple for local development, cargo lambda watch also simulate HTTP API and Funciton URL locally. You can access it directly. Here is the document: https://www.cargo-lambda.info/commands/watch.html#function-urls

Lambda Rust Runtime readme also give an example [here](https://github.com/awslabs/aws-lambda-rust-runtime#cargo-lambda). 

```shell
curl -v -X POST \
  'http://127.0.0.1:9001/lambda-url/<lambda-function-name>' \
  -H 'content-type: application/json' \
  -d '{ "command": "hi" }'
```

**Comment by davehorner** [comment]
@bnusunny thank you for your helpful responses.
closing this issue; solution has been provided and there is another ticket to represent the errant behavior.
