### ISSUE TITLE
Issue building library that statically links. 

### ISSUE THREAD

**Issue by markjohndoyle** [cargo-lambda/cargo-lambda#390]
This may be a zigbuild dependency issue, not sure.

I'm building a lambda that uses rdkafka which in turn uses the rdkafka-sys.

When running `cargo build --release` which uses zig I get an error that the subcommand qc is unknown.

I've tracked this down something running the zigbuild `ar` command with options `qc`. It don't know what generates this file but it starts like this:

`.cache/cargo-zigbuild/0.14.5/ar qc librdkafka.a CMakeFiles/rdkafka.dir/crc32c.c.o CMake....` it continues with all the object files.

If I run `.cache/cargo-zigbuild/0.14.5/ar` it doesn't appear to be the zig ar command, the output is as follows:

```
❯ .cache/cargo-zigbuild/0.14.5/ar
Usage: cargo <COMMAND>

Commands:
  lambda  Cargo Lambda is a CLI to work with AWS Lambda functions locally
  help    Print this message or the help of the given subcommand(s)

Options:
  -h, --help  Print help information
 ```

whereas the snap version of zig:
```
OVERVIEW: LLVM Archiver

USAGE: ar [options] [-]<operation>[modifiers] [relpos] [count] <archive> [files]
       ar -M [<mri-script]

OPTIONS:
  --format              - archive format to create
    =default            -   default
    =gnu                -   gnu
    =darwin             -   darwin
    =bsd                -   bsd
    =bigarchive         -   big archive (AIX OS)
  --plugin=<string>     - ignored for compatibility
  -h --help             - display this help and exit
  --output              - the directory to extract archive members to
  --rsp-quoting         - quoting style for response files
    =posix              -   posix
    =windows            -   windows
  --thin                - create a thin archive
  --version             - print the version and exit
  -X{32|64|32_64|any}   - object mode (only for AIX OS)
  @<file>               - read options from <file>

OPERATIONS:
  d - delete [files] from the archive
  m - move [files] in the archive
  p - print contents of [files] found in the archive
  q - quick append [files] to the archive
  r - replace or insert [files] into the archive
  s - act as ranlib
  t - display list of files in archive
  x - extract [files] from the archive

```

The build works if I set `--compiler cargo` but then I can't use different targets.

The project declares the dependency as follows:
`rdkafka = { version = "0.25.0", features = ["cmake-build"] }`

The specific error is as follows:
```
error: failed to run custom build command for `rdkafka-sys v3.0.0+1.6.0`

Caused by:
  process didn't exit successfully: `/home/---/target/release/build/rdkafka-sys-48459ad2a9de2485/build-script-build` (exit status: 101)
```
This suggests it may be an rdkafka-sys issue, but, as I say, the build does work when using `--compiler cargo`.

I know cargo-lamda uses cargo-zigbuild = "0.14.5" and that appears to be what the cmake process is trying to execute. Could it be some kind of incompatibility between rdkafka-sys and cargo-lambda?

**Comment by messense** [comment]
This needs a bit of hack to support, see

https://github.com/rust-cross/cargo-zigbuild/blob/14fffd84d4ee7bc3aaa64e7d304cbc82ab2ca780/src/bin/cargo-zigbuild.rs#L34-L42
