### ISSUE TITLE
Default template from cargo lambda new generates unused warnings

### ISSUE THREAD

**Issue by timClicks** [cargo-lambda/cargo-lambda#394]
We currently generate unused warnings from the boilerplate function generated by `cargo lambda new`. It's slightly off-putting to people who are starting, because warnings are scary.

We currently use this function signature:

```rust
async fn function_handler(event: Request) -> Result<Response<Body>, Error> {
   // ..
}
```

Perhaps we should simply add an underscore to `event`, e.g.:

```rust
async fn function_handler(_event: Request) -> Result<Response<Body>, Error> {
   // ..
}
```

**Comment by greenwoodcm** [comment]
i support that change

**Comment by timClicks** [comment]
Done :)
