### ISSUE TITLE
Add a `deploy` subcommand that uploads functions to lambda

### ISSUE THREAD

**Issue by calavera** [cargo-lambda/cargo-lambda#4]
`cargo lambda deploy` should take the content of `target/lambda` and upload it to lambda.

It should probably need a way to know if the function already exists, and if so, it'd change the function's version

**Comment by calavera** [comment]
I'm going to work on this command next.

**Comment by fancywriter** [comment]
@calavera great, it's not in the latest 0.6.2 version yet, correct? Any plans for new release?

**Comment by calavera** [comment]
@fancywriter I want to get this fix in https://github.com/cargo-lambda/cargo-lambda/pull/79. I'll release 0.7 as soon as that's working

**Comment by calavera** [comment]
@fancywriter I just published 0.7 in crates.io. The static binaries are building right now, and will show up in the releases section in about 30 minutes.
