### ISSUE TITLE
Implement streaming responses in `watch`

### ISSUE THREAD

**Issue by calavera** [cargo-lambda/cargo-lambda#477]
The `watch` subcommand doesn't support Lambda streaming responses, we need to implement it.

See https://github.com/awslabs/aws-lambda-rust-runtime/issues/665

**Comment by emilHof** [comment]
oh, yes, that is a very good consideration!!

where would you think are the places in the code base that would need to be adjusted to implement this feature? would some work likely need to be done in [`crates/cargo-lambda-watch`](https://github.com/cargo-lambda/cargo-lambda/tree/main/crates/cargo-lambda-watch)? in particular in `src/scheduler.rs` and `src/watcher.rs`, or is this instead a limitation of [`src/runtime`](https://github.com/cargo-lambda/cargo-lambda/tree/main/crates/cargo-lambda-watch/src/runtime) and how responses from functions are routed back to the requestee?

**Comment by emilHof** [comment]
@calavera, oh alright.. yea that would make sense! right now, it seems like it might be implement with a request queue in which incoming requests are placed alongside a `tokio::oneshot::channel`. The response is then sent back over that `oneshot::channel`. In particular here is where it fowards the request to the runtime:
 https://github.com/cargo-lambda/cargo-lambda/blob/0abe2f2d010e24043e52223cec09372b4f662f13/crates/cargo-lambda-watch/src/trigger_router.rs#L206-L231
and then here is where it returns the invocation response as far is i can tell:
https://github.com/cargo-lambda/cargo-lambda/blob/0abe2f2d010e24043e52223cec09372b4f662f13/crates/cargo-lambda-watch/src/runtime/functions_router.rs#L174-L188

though, how to change this to support streaming... what do you think ?
