### ISSUE TITLE
Watch process goes into an infinite rebuild loop when a project contains `.gitignore` that ignores everything

### ISSUE THREAD

**Issue by alex35mil** [cargo-lambda/cargo-lambda#669]
`cargo lambda watch` goes into an infinite rebuild loop when a project contains a subfolder with a `.gitignore` with the following contents:

```
*
```

Reproduction steps:
1. Generate a new cargo lambda project.
2. Add `foo/.gitignore` with the provided contents.
3. Run `cargo lambda watch`.

---

After I figured out the cause and filled in this issue, I found a workaround: ignore the `foo` folder in the root `.gitignore`. Still submitting it to raise awareness.

**Comment by sam-rusty** [comment]
This saved me a lot of time, i had the subfolder with .gitignore and I came to know after reading this issue that its a bug, moving that .gitignore content to main .gitignore solved the problem.

**Comment by calavera** [comment]
Fixing this probably requires upgrading Watchexec.

**Comment by calavera** [comment]
I finally managed to create a fix for this without having to do any upgrades. I'll probably do a release tomorrow or Thursday with the changes in #737 in it.
