### ISSUE TITLE
How to serve `watch` with https?

### ISSUE THREAD

**Issue by simbleau** [cargo-lambda/cargo-lambda#674]
Is there any documentation on how to serve via https and self-signed certs?

I currently use `cargo lambda watch` to serve my backend locally, which becomes available at `http://localhost.myorg.com:9000` (I have this in my /etc/hosts). My react frontend application uses https self-signed certs, and won't speak to my backend due to mixed-content. It would be great to see self-signed certs supported and easy to use.

Proposing:
```sh
cargo lambda watch --cert-file ~/.cert/cert.pem --key-file ~/.cert/key.pem
```

**Comment by simbleau** [comment]
I gave it a 5 minute shot, no dice.

Currently the `watch` command does this: `axum::Server::bind(&socket_addr)`,

and I found there is a library called `axum_server` that provides a TLS acceptor, e.g.

```rust
    let config = RustlsConfig::from_pem_file(
        "examples/self-signed-certs/cert.pem",
        "examples/self-signed-certs/key.pem",
    )
    .await
    .unwrap();

    let addr = SocketAddr::from(([127, 0, 0, 1], 3000));
    println!("listening on {}", addr);
    axum_server::bind_rustls(addr, config)
        .serve(app.into_make_service())
        .await
        .unwrap();
```

However this wasn't readily compatible with how you're doing things, or accepting new config flags through the CLI...

It would probably take an hour or more to figure this out, and I'm low on time. I'll leave this open to the next person who stumbles on this issue.

**Comment by calavera** [comment]
One main issue that is this project still depends on Hyper 0.14. After doing the upgrade of the Lambda runtime from 0.14 to 1, I kinda don't to do any other upgrades but at some point, I guess we should. 😅
