### ISSUE TITLE
`cargo lambda build` cannot find `zig` after installation in Git bash for Windows

### ISSUE THREAD

**Issue by DrewMcArthur** [cargo-lambda/cargo-lambda#678]
Hey! I'm operating on a windows laptop, and function via git bash.

Here's my output to running `cargo lambda build --release`
```
Building the release version of the Rust Lambda...
> Zig is not installed in your system.
How do you want to install Zig? Install with Pip3 (Python 3)
▪▪▪▪▪ Zig installed
Error:   × Failed to find zig

  Was this error unexpected?
  Open an issue in https://github.com/cargo-lambda/cargo-lambda/issues
```
running `pip install zig`
```
$ pip install zig
Requirement already satisfied: zig in c:\users\dmcarthur\appdata\local\continuum\anaconda3\lib\site-packages (1.0.dev0)
```

but it's not on my path:
```
$ which zig
which: no zig in (...
```

I'm sure this is an edge case, and relatively easily solvable.  After adding that directory to my path
```
export PATH="/c/Users/dmcarthur/appdata/local/continuum/anaconda3/lib/site-packages/ziglang/:$PATH"
```

then `which zig` and `cargo lambda build --release` work great!  Just wanted to bring this to your attention, in case this is something you wanted to incorporate into the tool.  Thanks for your work on this!

**Comment by calavera** [comment]
I'm closing this since I don't think it's actionable unfortunately.
