### ISSUE TITLE
`cargo lambda build` outputs artifacts to a fixed path, unlike `cargo build`

### ISSUE THREAD

**Issue by miceg** [cargo-lambda/cargo-lambda#686]
[`cargo` normally outputs *executables*](https://doc.rust-lang.org/cargo/guide/build-cache.html) to either:

* `target/$profile/binary-name`: for native binaries
* `target/$triple/$profile/binary-name`: for cross-compiled binaries with `--target $triple`

Because binaries for each build profile and target architecture is output to a different path, you always know which one you're working with. `cargo run` accepts similar arguments to `cargo build`, and will automatically rebuild the code as needed.

`cargo lambda build` doesn't follow this convention.

## Current behaviour

`cargo lambda build` *always* outputs the `bootstrap` executable (or `bootstrap.zip`) to `target/lambda/$package/`, regardless of build profile (`debug` / `release`) and whether it was configured to use a cross-compiler.

For example, building a [simple demo project](https://github.com/awslabs/aws-lambda-rust-runtime/tree/main/examples/http-axum) on a Linux `aarch64` system:

```
$ cargo lambda build --release -c cargo -o zip --x86-64
...
    Finished `release` profile [optimized] target(s) in 25.64s

$ tree target/
target/
├── CACHEDIR.TAG
├── lambda
│   └── hello-lambda-rust
│       └── bootstrap.zip
├── release
│   └── ...
└── x86_64-unknown-linux-gnu
    ├── CACHEDIR.TAG
    └── release
        ├── ...
        ├── examples
        ├── hello-lambda-rust
        ├── hello-lambda-rust.d
        └── incremental
```

Using a fixed path regardless of build configuration means that if you ever build a function with a different configuration to the production deployment, other subcommands like `cargo lambda deploy` are vulnerable to races (eg: with IDEs automatically building code), making it easy to unintentionally deploy the wrong configuration (profile or architecture) of a binary.

While I'm seeing this with `cargo lambda build -c cargo`, I believe the issue also affects the `cross` and Zig backends, because [`cargo lambda deploy` tries fixed paths by default](https://github.com/cargo-lambda/cargo-lambda/blob/70a08f219c527f42968b28ffac8eb3cd8049b3d9/crates/cargo-lambda-build/src/archive.rs#L139-L154).

## Expected behaviour

`cargo lambda build` should output binaries to:

* `target/$profile/lambda/$package/bootstrap(.zip)`: for native binaries
* `target/$target/$profile/lambda/$package/bootstrap(.zip)`: for cross-compiled binaries

This could be a breaking change for anything that expected binaries in their current locations.

`cargo lambda deploy` should accept similar flags to `cargo lambda build`, so that it can explicitly select a build profile and architecture, and use the same defaults, so that their behaviour is not affected by alternative configurations.

It would be nicer still if `cargo lambda deploy` could trigger a `build` at the same time (like how `cargo run` works), so it could do everything in one command.

**Comment by calavera** [comment]
This is by design, and I'm not going to change it. Having a determined output path is actually a feature for many people that don't care much about where the binaries are located.
