### ISSUE TITLE
Cargo lambda build --release gives Zig error - UnableToSpawnSelf

### ISSUE THREAD

**Issue by DoIevenLift** [cargo-lambda/cargo-lambda#698]
Hi, 

Unsure if this is the best place to post - if not let me know.

Using cargo lambda build --release gives this error **when** specific crate is added:

![image](https://github.com/user-attachments/assets/0c88348d-1096-4e54-a4db-58f2a7cd4746)

I can see there was an old issue for this related to this which can be found here: [https://github.com/cargo-lambda/cargo-lambda/pull/665](url) & on the zig side - [https://github.com/ziglang/zig/issues/10881](url) both of these have been merged etc. I've checked clang version (assuming this is correct) and it is:

![image](https://github.com/user-attachments/assets/6bc312f9-e417-4561-b4a3-6c8c1524e7b8)

I have narrowed this down to a specific crate (excluding any dependencies they use) which is - [https://crates.io/crates/postgrest](url). If I remove this crate, cargo lambda build --release will build to completion. 

During the build phase no errors pop up on any of the crates including the one above, however when it gets to compiling it'll hit the error presented. 

If there is anything else let me know

Thanks!

**Comment by calavera** [comment]
Did you check that you're using a recent version of Zig? If you have multiple in your path, it might be using the wrong one. If you're using Cargo Lambda 1.4.0, you can check with `cargo lambda system`

**Comment by DoIevenLift** [comment]
Hi @calavera , 

Thanks for taking the time to reply. Just wanted to confirm that this was a zig version issue. Upgraded the right one to 0.13 and compiled no issues. 

Thanks again
