### ISSUE TITLE
"Invalid cross-device link" when running `cargo lambda new blah` on Manjaro

### ISSUE THREAD

**Issue by sdd** [cargo-lambda/cargo-lambda#70]
   ~/projects  cargo lambda new sa-solver-sns-result-ws-dispatcher                                                                                                         
? Is this function an HTTP function? No
? AWS Event type that this function receives sns::SnsEvent
Error: 
  × failed to move package: from "/tmp/.tmpX6qXqg" to "sa-solver-sns-result-ws-dispatcher"
  ╰─▶ Invalid cross-device link (os error 18)

 ~/projects  cargo lambda new sa-solver-sns-result-ws-dispatcher                                                                                                         
? Is this function an HTTP function? No
? AWS Event type that this function receives sns::SnsEvent
Error: 
  × failed to move package: from "/tmp/.tmpX6qXqg" to "sa-solver-sns-result-ws-dispatcher"
  ╰─▶ Invalid cross-device link (os error 18)

    ~/projects  uname -a                                                                                                                                                   1 ✘  18s   base  
Linux gauss 5.10.105-1-MANJARO #1 SMP PREEMPT Fri Mar 11 14:12:33 UTC 2022 x86_64 GNU/Linux
    ~/projects  cargo --version                                                                                                                                                      ✔  base  
cargo 1.62.0-nightly (dba5baf 2022-04-13)

**Comment by calavera** [comment]
Thanks for opening this issue!

It looks like Rust `file:rename` can fail in some Linux kernels, according to a similar issues in rustup: https://github.com/rust-lang/rustup/issues/1239

The solution seems to be to capture the error and do a Copy+Delete in those cases.

**Comment by sdd** [comment]
Aah, interesting. I'd expect that having `/tmp` on a different device would be not uncommon on *nix systems.

Rustup's fix involved them implementing some util functions themselves to fall back to copy+delete on a failed move/rename, but this seems like the kind of thing that should be in an existing library though rather than copy/pasting code from there.

 `fs_extra`'s [move_dir](https://docs.rs/fs_extra/1.2.0/fs_extra/dir/fn.move_dir.html) seems like a candidate but I'm not sure if `fs_extra` is still maintained.

**Comment by sdd** [comment]
Ha, just seen your PR after writing the above, thanks for the quick turnaround!

**Comment by calavera** [comment]
@sdd I'll probably release a new version in the next couple of days. Meanwhile you can install it by cloning the repo:

```
git clone https://github.com/cargo-lambda/cargo-lambda
cd cargo-lambda
cargo install --force --path crates/cargo-lambda-cli
```

**Comment by sdd** [comment]
Will give it a go tomorrow, thanks!

**Comment by sdd** [comment]
Hi @calavera - unfortunately that change didn't fix the problem. If I change `rename` to the below then it works - but it requires the unstable `#![feature(io_error_more)]`:

```rust
pub fn rename<P, Q>(from: P, to: Q) -> io::Result<()>
where
    P: AsRef<Path>,
    Q: AsRef<Path>,
{
    match fs::rename(&from, &to) {
        Ok(ok) => Ok(ok),
        Err(e) => match e.kind() {
            io::ErrorKind::CrossesDevices => {
                match copy_and_delete(from, to) {
                    Ok(()) => Ok(()),
                    Err(_) => Err(e),
                }
            },
            _ => Err(e),
        },
    }
}
```

**Comment by sdd** [comment]
Sounds like `ErrorKind::Other` does not get returned anymore: https://github.com/rust-lang/rust/pull/85746

I think we can check against the error code directly for now until this is `io_error_more` is stabilized: https://github.com/rust-lang/rust/issues/86442#issuecomment-889391007

**Comment by sdd** [comment]
Aah, this works, without needing `io_error_more`:

```rust
pub fn rename<P, Q>(from: P, to: Q) -> io::Result<()>
where
    P: AsRef<Path>,
    Q: AsRef<Path>,
{
    match fs::rename(&from, &to) {
        Ok(ok) => Ok(ok),
        Err(e) if Some(libc::EXDEV) == e.raw_os_error() => {
            match copy_and_delete(from, to) {
                Ok(()) => Ok(()),
                Err(_) => Err(e),
            }
        },
        Err(e) => Err(e),
    }
}
```
