### ISSUE TITLE
Why does it need Zig?

### ISSUE THREAD

**Issue by sryze** [cargo-lambda/cargo-lambda#700]
What does this tool need Zig for exactly? It seems to be written in Rust from what I can see. I just don't like bloated dependencies like ziglang which is ~80MB in size.

```
Downloading ziglang-0.13.0-py3-none-win_amd64.whl (80.4 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 80.4/80.4 MB
```

**Comment by Dgame** [comment]
For cross compiling, but there are alternatives: https://www.cargo-lambda.info/guide/cross-compiling.html

**Comment by sryze** [comment]
Yes, thanks, I've already found this info in the docs. I didn't realize that. I thought that the Rust compiler could do it out of the box.

**Comment by sryze** [comment]
I would make sense to not make ziglang a hard dependency in pip though (IMO).
