### ISSUE TITLE
Request update in nixpkgs

### ISSUE THREAD

**Issue by albertomolinafelipe** [cargo-lambda/cargo-lambda#703]
The current version in nixpkgs is 1.2.1, which uses a version of cargo-zigbuild which has a memcp bug
I attempted to build it from source, but with no success
Please consider updating to 1.4,

Thanks

**Comment by calavera** [comment]
You might need to update the index. 1.4.0 was merged a few weeks ago: https://github.com/NixOS/nixpkgs/pull/342505. If you have any problem upgrading, feel free to open an issue in the nixpkgs repository.
