### ISSUE TITLE
Role credentials with Source Identity set cause errors in `cargo lambda deploy`

### ISSUE THREAD

**Issue by perpil** [cargo-lambda/cargo-lambda#724]
I was following the instructions on Chapter 2 in the `Crafting Lambda in Rust` book and got to deploying my Lambda the first time using `cargo lambda deploy`.  I am using role credentials with a [SourceIdentity](https://docs.aws.amazon.com/STS/latest/APIReference/API_AssumeRole.html#:~:text=SourceIdentity) set. The deployment fails due to the fact the trust policy of the role that is created doesn't have `sts:SetSourceIdentity` permissions so it can't propogate the source identity.  I was able to get it to succeed by manually adding that `sts:SetSourceIdentity` to the trust policy.

Does it make sense to add those permissions [here](https://github.com/cargo-lambda/cargo-lambda/blob/7735f13ac55bfcd34eb87a1e0d4e940f68c8d4ad/crates/cargo-lambda-deploy/src/roles.rs#L30)?  They are only really necessary on the caller's principal, not the `lambda.amazonaws.com` principal so you might want to have 2 Allow statements. i.e.

```json
{
	"Version": "2012-10-17",
	"Statement": [
		{
			"Effect": "Allow",
			"Principal": {
				"Service": "lambda.amazonaws.com",
				"AWS": "arn:aws:sts::<removed>:assumed-role/speedrun-Admin/perpil"
			},
			"Action": [
				"sts:AssumeRole"
			]
		},
                {
			"Effect": "Allow",
			"Principal": {
				"AWS": "arn:aws:sts::<removed>:assumed-role/speedrun-Admin/perpil"
			},
			"Action": [
				"sts:SetSourceIdentity"
			]
		}
				
	]
}
```

Also, I was momentarily confused due to [this error message](https://github.com/cargo-lambda/cargo-lambda/blob/7735f13ac55bfcd34eb87a1e0d4e940f68c8d4ad/crates/cargo-lambda-deploy/src/roles.rs#L125
) not displaying the full role arn correctly, the formatting mangles it and it looks like this:

<img width="1212" alt="image" src="https://github.com/user-attachments/assets/de62bdf9-066a-4d36-8ccd-5a6822b8cb09">

It appears what comes after the second dash in the uuid of the role arn is being used to do some formatting instead of being used as is.

**Comment by calavera** [comment]
I think that makes sense, although I’m not super familiar with `SourceIdentity`. Feel free to open a PR to add that statement, otherwise, I can add it myself soon.

I’m not sure what’s going on with the formatting, it’s probably a problem with of spacing between the library I use to display the errors and the terminal. I’ll have to investigate it.

**Comment by perpil** [comment]
Thanks David! I linked a PR that adds support for credentials that have SourceIdentity set. I was unable to figure out the formatting of the error issue.

**Comment by calavera** [comment]
For what it's worth, you can also create your own role in your account with the statement you need, and pass it as a flag to the deploy command: https://www.cargo-lambda.info/commands/deploy.html#iam-roles

**Comment by calavera** [comment]
The fix for this is merged now. I'll probably release a patch version with it this week.
