### ISSUE TITLE
Building a cross-compiled, statically linked binary on Linux?

### ISSUE THREAD

**Issue by mwudtke** [cargo-lambda/cargo-lambda#734]
I'm trying to cross-compile using the following command:

```
cargo lambda build --compiler cargo --extension --release --target x86_64-unknown-linux-musl
```

This command fails with the message `invalid options: --compiler=cargo is only allowed on Linux` if I run it from an ARM machine.

I see that the build process disallows statically linking when cross-compiling on Linux hosts, per the logic from [this section](https://github.com/cargo-lambda/cargo-lambda/blob/main/crates/cargo-lambda-build/src/lib.rs#L172-L179). Specifically, the [check for `is_static_linking`](https://github.com/cargo-lambda/cargo-lambda/blob/main/crates/cargo-lambda-build/src/target_arch.rs#L80) returns false:

```
    #[cfg(target_os = "linux")]
    pub fn is_static_linking(&self) -> bool {
        self.rustc_target == format!("{}-unknown-linux-musl", ARCH)
    }
```

Since the `rustc_target` value will not match the `ARCH` environment variable.

Is it possible to relax this restriction? Or is there something inherent to the compilation process that will lead it to fail, hence the conditional that prevents it from working?

**Comment by calavera** [comment]
it's probably a bug in the way that that check is supposed to work. It might make more sense to do this:

```rust
    #[cfg(target_os = "linux")]
    pub fn is_static_linking(&self) -> bool {
        self.rustc_target == "x86_64-unknown-linux-musl" || self.rustc_target == "aarch64-unknown-linux-musl"
    }
```

**Comment by calavera** [comment]
I put up a quick PR to fix it: https://github.com/cargo-lambda/cargo-lambda/pull/736. I'll probably do a new release this week with this and other changes.
