### ISSUE TITLE
cargo lambda deploy getting AccessDeniedException out of nowhere, requesting ec2:DescribeSecurityGroups

### ISSUE THREAD

**Issue by edeetee** [cargo-lambda/cargo-lambda#751]
This was working a week ago, now I'm getting weird AccessDeniedExceptions

I have an iam user with the following permissions:
```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": [
                "iam:CreateRole",
                "iam:AttachRolePolicy",
                "iam:UpdateAssumeRolePolicy",
                "iam:PassRole"
            ],
            "Resource": [
                "arn:aws:iam::622290641040:role/AWSLambdaBasicExecutionRole",
                "arn:aws:iam::622290641040:role/lambda-role*"
            ]
        },
        {
            "Effect": "Allow",
            "Action": [
                "lambda:CreateFunction",
                "lambda:UpdateFunctionCode",
                "lambda:GetFunction",
                "lambda:UpdateFunctionConfiguration"
            ],
            "Resource": "arn:aws:lambda:ap-southeast-2:622290641040:function:*"
        }
    ]
}
```

I didn't have the lambda:UpdateFunctionConfiguration a week ago. I initially got an error saying it was required, which I thought was reasonable as you mention this in your docs. However, the ec2 permissions are much weirder.

The error in question:

```
  ╰─▶ Error { code: "AccessDeniedException", message: "Your access has
      been denied by EC2, please make sure your request credentials have
      permission to DescribeSecurityGroups for sg-0fd92074f86a24867,sg-
      0269e43fabe809790. EC2 Error Code: UnauthorizedOperation. EC2 Error
      Message: You are not authorized to perform this operation. User:
      arn:aws:iam::622290641040:user/gh_action_deploy is not authorized
      to perform: ec2:DescribeSecurityGroups because no identity-based
      policy allows the ec2:DescribeSecurityGroups action", aws_request_id:
      "fd473534-7db9-47aa-9961-9f35dc6bf67a" }
```

**Comment by calavera** [comment]
Which version of Cargo Lambda are you using?

**Comment by edeetee** [comment]
➜ cargo lambda --version
cargo-lambda 1.2.1 (12f9b61 2024-04-05Z)

**Comment by calavera** [comment]
Then, it must be some kind of change in your AWS account because the required permissions are hardcoded in each binary, and no changes has been made to that version.

A quick google search showed me this: 

> To attach your function to a VPC, Lambda also needs to verify network resources using your IAM user role. Ensure that your user role has the following IAM permissions:
>    ec2:DescribeSecurityGroups
>
>   ec2:DescribeSubnets
>
>   ec2:DescribeVpcs

https://docs.aws.amazon.com/lambda/latest/dg/configuration-vpc.html

Is it possible that your AWS account has changed to put all your lambda functions in a VPC?

**Comment by edeetee** [comment]
I've had a VPC set up for a while to connect to RDS, definitely more than a week.
Maybe cargo-lambda wants to reset something in my lambda that causes it to update things it hasn't had to before?

**Comment by calavera** [comment]
It’s possible, because this command doesn’t have any state management at the moment, as [explained in the docs](https://www.cargo-lambda.info/commands/deploy.html#state-management). If the function is in a VPC, I’m guessing the Lambda control plane needs to check access permissions before performing any operation, and your IAM role doesn’t grant them.

**Comment by calavera** [comment]
I've added additional information about VPCs to the deployment docs: https://github.com/cargo-lambda/cargo-lambda/pull/753

You can try debugging what's being updated by adding the `-v` flag to the deploy command (`-v` for debug, `-vv` for trace).

I'm not sure I can help you further than that, but if you find any inconsistency on what's being deployed, I'll be happy to make adjustments to the command to make it more reliable.

**Comment by calavera** [comment]
I'm going to close this issue as it seems more like an account permissions issue. Feel free to start a discussion if you want to continue exploring improvements in this area.
