### ISSUE TITLE
ResourceConflictException message in version 1.6.1

### ISSUE THREAD

**Issue by rbox-risk** [cargo-lambda/cargo-lambda#759]
Thanks for great utility!

I'm building function lambda on windows with 
`--arm64` and 
`rustc 1.83.0 (90b35a623 2024-11-26)`. 
I plan to move to Github Action, when everything is working locally.

I was working with `cargo-lambda 1.5` and had no issues

Changing nothing else, I updated to `cargo-lambda 1.6.1 (782c01b 2024-12-21Z)` and now I see exception messages.

I'm performing simple builds and deploys as per CL 1.5:

`cargo lambda build --release --arm64`
then
`cargo lambda deploy --include ./cert`

upon deploy I see
`function is not ready for updates` or words to that effect
followed by the exception
`Error:   × failed to update function code`

If I run `deploy` with `--verbose` I see two `deploying function` messages, and a large config object followed by the exception

![image](https://github.com/user-attachments/assets/e9bb4578-2a0d-4fe7-8c56-c065585a865b)

If then look in the lambda console it does show its been touched...
![image](https://github.com/user-attachments/assets/29c444d7-9cb2-4cfd-b0d5-b18dc05717dc)

Could this be an issue with the `include` or with the default `iam`, or something else?

**Comment by calavera** [comment]
Lambda uses a state machine to make changes to your function. `An update is in progress` probably means that another process is currently making changes in your function's configuration.

I would need some more information to help you with this. Here are some questions:

- Do you have some kind of additional configuration besides the `--include` flag?
- Can you put the logs in a gist.github.com for me to take a look?
- Can you run the command with both versions with the `--dry` flag and put the output here? that will print some information about the deploy, without doing an actual deploy.

**Comment by calavera** [comment]
I think I found the issue. This new version is trying to update the configuration due to a new field added in 1.6, which should not be updated by default. I'll create a patch a release a new version by the end of this week.

**Comment by rbox-risk** [comment]
> Lambda uses a state machine to make changes to your function. `An update is in progress` probably means that another process is currently making changes in your function's configuration.
> 
> I would need some more information to help you with this. Here are some questions:
> 
> * Do you have some kind of additional configuration besides the `--include` flag?
> * Can you put the logs in a gist.github.com for me to take a look?
> * Can you run the command with both versions with the `--dry` flag and put the output here? that will print some information about the deploy, without doing an actual deploy.

Thanks for looking - just in case it helps:
* no extra configuration, other than a standard `profile.release` in `Cargo.toml`. This example was stripped back to a minimum
* I think you have possibly found the issue - but if it turns out not to be, yes absolutely can provide logs.  This is non-public data so I'll have to do so privately, etc. I will check back here though. 

Thanks again

**Comment by calavera** [comment]
Yeah, I was able to reproduce the problem with an include file. I also noticed that the state machine that handles updates was not doing the right thing because it should have waited for the unexpected configuration changes to be fully propagated. #760 fixes both issues.

**Comment by rbox-risk** [comment]
Ah yes - great. I confirmed the same. Created a totally new lambda from scratch that did nothing except echo request body. As soon as I `--include` the error appears. Thanks for fast looking.

**Comment by calavera** [comment]
👋 I've just released version 1.6.2 with these changes. Check out the release notes: https://github.com/cargo-lambda/cargo-lambda/releases/tag/v1.6.2
